### ISSUE TITLE
Trouble.

### ISSUE THREAD

**Issue by Artyom16RUS** [Artyom16RUS/Lego#3]
Проеблема такая, компьютер вспомнтаны отключается. После чего я потерял весь проект. Idea открывает пустые файлы, в них ни чего нет. Пытаюсь скачать с репозитория, от туда скачывается только сам проект без Commit и branch. Как можно скачать все сразу? В инете ненашел способа.

**Comment by coursar** [comment]
git clone и URL вашего репо

**Comment by coursar** [comment]
На лекции напомните - покажу.
